[[collection]]
type = "art_simple"
title = "Google Data Analytics"
subtitle = "Issued Jun 2024" # optional
link = "https://www.coursera.org/account/accomplishments/specialization/VXTZ7EFLXX2V" # optional
img = "img/cert/google_data_analytics.webp" # optional