[[collection]]
type = "card_simple"
title = "MMI Capital"
date = "Aug 2025 - Present"
# icon = ""
# link = "https://jienweng.com" # optional
content = "Frontend Web Developer"
featured = false  # optional

[[collection]]
type = "card_simple"
title = "ACTBuilder Actuarial Solution"
date = "Jul 2025 - Present"
# icon = "https://yt3.googleusercontent.com/kZo3aN6y8jir2NWOysuHt5vEixFTrdN0IESfzHhsKsmcqCuwhOIh3dy1Mzk0PRkt4JSVu6WjMCI=s160-c-k-c0x00ffffff-no-rj"
link = "https://actbuilder.com.my" # optional
content = "Techical Support"
featured = false  # optional

[[collection]]
type = "card_simple"
title = "Great Eastern Life Assurance"
date = "Oct 2024 - Jan 2025"
# icon = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_bwoq80vl_iPTGuE1xgdc3-9xLB1uJXq1mw&s"
link = "https://example.com" # optional
content = "Data Engineer Intern"
featured = false  # optional